apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app.kubernetes.io/instance: app
  name: app
  namespace: jultelegrafen
spec:
  commonName: jultelegrafen.middleware.se
  dnsNames:
    - jultelegrafen.middleware.se
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-middleware-se
  secretName: app-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app.kubernetes.io/instance: app
  name: stream-proxy
  namespace: jultelegrafen
spec:
  commonName: stream-proxy.middleware.se
  dnsNames:
    - stream-proxy.middleware.se
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-middleware-se
  secretName: stream-proxy-tls
