apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app
  namespace: jultelegrafen
spec:
  ingressClassName: nginx
  rules:
    - host: jultelegrafen.middleware.se
      http:
        paths:
          - backend:
              service:
                name: app
                port:
                  number: 8080
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - jultelegrafen.middleware.se
      secretName: app-tls
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stream-proxy
  namespace: jultelegrafen
spec:
  ingressClassName: nginx
  rules:
    - host: stream-proxy.middleware.se
      http:
        paths:
          - backend:
              service:
                name: stream-proxy
                port:
                  number: 443
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - stream-proxy.middleware.se
      secretName: stream-proxy-tls
