apiVersion: v1
kind: Service
metadata:
  labels:
    app: app
  name: app
  namespace: jultelegrafen
spec:
  ports:
    - name: 8080-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: app
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: stream-proxy
  name: stream-proxy
  namespace: jultelegrafen
spec:
  externalName: stream-proxy-2.middleware.se
  selector:
    app: stream-proxy
  sessionAffinity: None
  type: ExternalName
  ports:
    - name: 443-443
      port: 443
      protocol: TCP
      targetPort: 80
